!!com.appdynamics.cloud.aws.appregistry.ApplicationConfig

controllerAccount: "<controller-account-name>"
controllerUsername: "<controller-username>"
controllerPassword: "<controller-password>"
controllerHostName: "mydemo.saas.appdynamics.com"
controllerPort: 443
controllerSslEnabled: true

addAppIdToAppName: false

applicationNames:
  - AD-Travel
  - Ecommerce
  - AD-Movie Tickets Core